---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-service
spec:
  selector:
    app: nginx
    version: "1.16"
  ports:
  - protocol: TCP
    port: 9009
    targetPort: 80
  type: LoadBalancer